services:
  hapi:
    image: hapiproject/hapi:latest
    ports: ["8080:8080"]

  api:
    build:
      context: ./services/agents-service
      dockerfile: ../../Dockerfile.api
    environment:
      - FHIR_BASE_URL=http://hapi:8080/fhir
      - ALLOWED_ORIGINS=http://localhost:5173
    ports: ["8070:8000"]
    depends_on: [hapi]

  web:
    build:
      context: ./apps/web
      dockerfile: ../../Dockerfile.web
    environment:
      - VITE_FHIR_BASE_URL=http://localhost:8080/fhir
    ports: ["5173:5173"]
    depends_on: [api]
