services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:80"
    depends_on: [agents]
  agents:
    build:
      context: .
      dockerfile: services/agents-service/Dockerfile
    environment:
      - OPA_URL=http://opa:8181/v1/data/fhir/authz/allow
    ports:
      - "8070:8070"
  opa:
    image: openpolicyagent/opa:latest
    command: ["run","--server","/policies"]
    volumes: ["./opa/policies:/policies"]
    ports: ["8181:8181"]
  reverse:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.directory=/etc/traefik/"
    volumes:
      - "./infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    ports: ["8088:80","8089:8080"]
  # Opcionales
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: ["start-dev","--http-port","8081"]
    ports: ["8081:8081"]
    profiles: ["auth"]
  hapi:
    image: hapiproject/hapi:v7.4.0
    ports: ["8080:8080"]
    profiles: ["fhir"]
  otel:
    image: otel/opentelemetry-collector:0.99.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes: ["./infra/otel/config.yaml:/etc/otel/config.yaml:ro"]
  grafana:
    image: grafana/grafana:10.4.3
    ports: ["3000:3000"]
