name: api-ci
on: [push, pull_request]
jobs:
  api:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: services/agents-service } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic
      - run: python - << 'PY'
import sys; print("API CI OK")
PY
