name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/web build
      - run: pnpm -C apps/web test -- --run --coverage --reporter=dot
      - run: pnpm -C apps/web exec playwright install --with-deps
      - run: pnpm -C apps/web e2e -- --reporter=dot
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install ruff black
      - run: ruff --version && black --version
  fhir-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "21" }
      - run: curl -L -o validator_cli.jar https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
      - run: |
          if [ -d services/tests/fhir-examples ]; then \
            java -jar validator_cli.jar services/tests/fhir-examples/*.json -version 4.0; \
          else echo "No hay ejemplos FHIR"; fi
