name: Web Tests

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/web-test.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/web-test.yml"

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/web test:run
